# Change these first
owner: owlstake # Your GitHub organization or username, where this repository lives
repo: uptime-status # The name of this repository
sites:
  - name: Homepage
    url: https://owlstake.com
  - name: Explorer
    url: https://explorer.owlstake.com
  - name: Shentu RPC
    url: https://shentu-rpc.owlstake.com
  - name: Shentu API
    url: https://shentu-api.owlstake.com
    expectedStatusCodes:
      - 501
  - name: Aura RPC
    url: https://aura_6322-2-rpc.owlstake.com
  - name: Aura API
    url: https://aura_6322-2-api.owlstake.com
    expectedStatusCodes:
      - 501
  - name: Atom-1 RPC
    url: https://atomone-1-rpc.owlstake.com
  - name: Atom-1 API
    url: https://atomone-1-api.owlstake.com
    expectedStatusCodes:
      - 501
  - name: Dymension RPC
    url: https://dymension_1100-1-rpc.owlstake.com
  - name: Dymension API
    url: https://dymension_1100-1-api.owlstake.com
    expectedStatusCodes:
      - 501
  - name: Saga RPC
    url: https://ssc-1-rpc.owlstake.com
  - name: Saga API
    url: https://ssc-1-api.owlstake.com
    expectedStatusCodes:
      - 501
  - name: Seda RPC
    url: https://seda-1-rpc.owlstake.com
  - name: Seda API
    url: https://seda-1-api.owlstake.com
    expectedStatusCodes:
      - 501
  - name: Pell Testnet RPC
    url: https://ignite_186-1-rpc.owlstake.com
  - name: Pell Testnet API
    url: https://ignite_186-1-api.owlstake.com
    expectedStatusCodes:
      - 501
  - name: Seda Testnet RPC
    url: https://seda-1-testnet-rpc.owlstake.com
  - name: Seda Testnet API
    url: https://seda-1-testnet-api.owlstake.com
    expectedStatusCodes:
      - 501
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.owlstake.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/owlstake/owlstake/main/svg/logo-black.svg
  faviconSvg: https://raw.githubusercontent.com/owlstake/owlstake/main/svg/logo-black.svg
  name: Owlstake Server Status
  introTitle: "Owlstake Server Status"
  introMessage: "You can check the uptime and maintenance schedule notifications for Owlstake's server and services here."
  navbar:
    - title: Home
      href: https://owlstake.com
    - title: Owlstake Server Status
      href: /
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
i18n:
  footer: Copyright © 2023. All Rights Reserved by Owlstake.com
